spring.application.name=final_project
spring.datasource.url=jdbc:postgresql://110.74.194.124:5440/gatherly_db
spring.datasource.username=gatherly
spring.datasource.password=gatherly

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eventmaster168@gmail.com
spring.mail.password=qevazdqwbxwkgwao
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.mime.charset=UTF